
#define WINDOW_CLASS_NAME L"Castlevania"
#define MAIN_WINDOW_TITLE L"Castlevania"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 255, 200)
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 480
#define GAME_WORLD_Y 64

#define MAX_FRAME_RATE 120

#define ID_TEX_SIMON 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_WHIP 31
#define ID_TEX_TORCH 40
#define ID_TEX_ZOMBIE 50
#define ID_TEX_ITEM_HEART 500
#define ID_TEX_TILESET_1 1000
#define ID_TEX_TILESET_2 1001

#define ID_TILE_BACKGROUND 1
#define ID_TILE_OBJECT_BOUNDMAP 2
#define ID_TILE_OBJECT_GROUND 3
#define ID_TILE_OBJECT_SIMON 5
#define ID_TILE_OBJECT_TORCH 6
#define ID_TILE_OBJECT_ZOMBIE 6

///
///ITEM
///
#define ITEM_STATE_HIDING 100
#define HEART_STATE_BIGHEART 200
#define HEART_STATE_SMALLHEART 300
#define HEART_BIG 1
#define HEART_SMALL 0;
#define HEART_ANI_SMAIL 0
#define HEART_ANI_BIG 1
#define HEART_BBOX_HEIGHT 30
#define HEART_BBOX_WIDTH 31
#define HEART_GRAVITY			0.0002f


#define GAME_STATE_01 100
#define GAME_STATE_02 200
#define GAME_STATE_03 300


